name: Rijsttafel
favicon: null
layout_spectrum: 0.3305076980032027
typography_spectrum: 0.24166388087905943
title: Branding Agency
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#FF6700'
    - '#EBEBEB'
    - '#C0C0C0'
    - '#3A6EA5'
    - '#004E98'
  brandStrength: 0.1025005909614265
  lightness: 0.020439567044377327
  saturation: 0.40848013246431947
  rhythmicContrast: 0.8600477366708219
purpose: []
